name: Auto Label PR

on:
- pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
    
  check-labels:
    needs: labeler
    runs-on: ubuntu-latest
    steps:
      - name: Check for DoNotMerge label
        uses: actions/github-script@v7
        with:
          script: |
            const labels = context.payload.pull_request.labels.map(l => l.name);
            console.log(`PR has labels: ${labels.join(', ')}`);
            if (labels.includes('DoNotMerge')) {
              core.setFailed('This PR is labeled as DoNotMerge!');
            }