name: Check DoNotMerge Label

on:
  workflow_call:

jobs:
  fail-by-label:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR is labeled as DoNotMerge
        run: |
          LABELS=$(echo '${{ toJson(github.event.pull_request.labels) }}' | jq -r '.[].name')
          echo -e "This PR has the following Labels:\n$LABELS"
          if [[ $LABELS == *"DoNotMerge"* ]]; then
            echo "This PR is labeled as DoNotMerge!"
            exit 1
          fi