name: Label Check

on:
  pull_request:
      branches: ["*"]
      types: [labeled, unlabeled, opened, synchronize, auto_merge_enabled]

jobs:
  check-labels:
    uses: ./.github/workflows/check-do-not-merge.yml
